apiVersion: apps/v1
kind: Deployment
metadata:
  name: idempotency-db
  labels:
    component: idempotency-db
spec:
  replicas: 1
  selector:
    matchLabels:
      component: idempotency-db
  template:
    metadata:
      labels:
        component: idempotency-db
    spec:
      volumes:
        - name: sqlserver-storage
          persistentVolumeClaim:
            claimName: idempotency-db-pvc
      containers:
        - name: idempotency-db
          image: mcr.microsoft.com/mssql/server:2017-latest
          imagePullPolicy: Never
          ports:
            - containerPort: 1434
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: SwN12345678
          volumeMounts:
            - name: sqlserver-storage
              mountPath: /var/opt/mssql